GET https://api.easybill.de/rest/v1/customers
Authorization: Bearer ERqN6t9TKkhErANcOdpBj7hYmrgzVdiE7xBqQRQQVN3df1ZhNcmWbQ9gheNSNq4o
###

POST https://api.easybill.de/rest/v1/customers
Authorization: Bearer ERqN6t9TKkhErANcOdpBj7hYmrgzVdiE7xBqQRQQVN3df1ZhNcmWbQ9gheNSNq4o

{
  "acquire_options": null,
  "bank_account": null,
  "bank_account_owner": null,
  "bank_bic": null,
  "bank_code": null,
  "bank_iban": null,
  "bank_name": null,
  "birth_date": "2016-12-31",
  "cash_allowance": null,
  "cash_allowance_days": 7,
  "cash_discount": null,
  "cash_discount_type": null,
  "city": "Kaarst",
  "state": "NRW",
  "company_name": "easybiadll GmbH",
  "country": "DE",
  "delivery_title": "Dr.",
  "delivery_city": null,
  "delivery_state": "NRW",
  "delivery_company_name": null,
  "delivery_country": null,
  "delivery_first_name": null,
  "delivery_last_name": null,
  "delivery_personal": false,
  "delivery_salutation": 0,
  "delivery_street": null,
  "delivery_suffix_1": null,
  "delivery_suffix_2": null,
  "delivery_zip_code": null,
  "emails": [
    "max.mustermann@easybill.de"
  ],
  "fax": "+49 2154 89701 29",
  "first_name": "Max",
  "grace_period": null,
  "due_in_days": null,
  "group_id": null,
  "info_1": null,
  "info_2": null,
  "internet": "https://www.easybill.de",
  "last_name": "Mustermann",
  "login_id": 1,
  "mobile": null,
  "note": null,
  "number": "string",
  "payment_options": null,
  "personal": false,
  "phone_1": "+49 2154 897021 20",
  "phone_2": null,
  "postbox": null,
  "postbox_city": null,
  "postbox_state": "NRW",
  "postbox_country": null,
  "postbox_zip_code": null,
  "sale_price_level": null,
  "salutation": 1,
  "sepa_agreement": null,
  "sepa_agreement_date": null,
  "sepa_mandate_reference": null,
  "since_date": null,
  "street": "Düsselstr. 21",
  "suffix_1": null,
  "suffix_2": null,
  "tax_number": null,
  "court": "Berlin",
  "court_registry_number": "HRB XXXXX X",
  "tax_options": null,
  "title": null,
  "vat_identifier": "DE814878557",
  "zip_code": "41564",
  "documentPdfType": "default",
  "buyer_reference": "string",
  "foreign_supplier_number": "string"
}

###

PUT https://api.easybill.de/rest/v1/customers/1201510832
Authorization: Bearer ERqN6t9TKkhErANcOdpBj7hYmrgzVdiE7xBqQRQQVN3df1ZhNcmWbQ9gheNSNq4o
{
  "id":4
}

###

DELETE  https://api.easybill.de/rest/v1/customers/1201510832
Authorization: Bearer ERqN6t9TKkhErANcOdpBj7hYmrgzVdiE7xBqQRQQVN3df1ZhNcmWbQ9gheNSNq4o
{
  "id":4
}