POST https://permatech43.scoro.com/api/v2/file/list
content-type: application/json

{
    "apiKey": "ScoroAPI_32abdfb0507d7b0",
    "lang": "eng",
    "company_account_id": "permatech43",
    "request": {}
}