
POST https://api.easybill.de/rest/v1/webhooks
Authorization: Bearer kBBUn0ek3BAy149L1LAhyhdyQPdDPxedlPc8XJO147hYx3FYuXLCv71S2zhxo3BB


{
  "content_type": "json",
  "description": "Document create",
  "events": [
    "document.create"
  ],
  "is_active": true,
  "secret":"false",
  "url":  "https://03b9-2405-201-6007-5b7c-d169-a8a1-2862-d184.ngrok.io/easyBill"
}
###




GET https://api.easybill.de/rest/v1/webhooks
Authorization: Bearer kBBUn0ek3BAy149L1LAhyhdyQPdDPxedlPc8XJO147hYx3FYuXLCv71S2zhxo3BB


###